$Script = <<-Script
sudo apt-get update
sudo apt-get install apache2 -y
sudo apt-get install ufw -y
sudo ufw allow from 10.0.2.2 to any port 22
sudo ufw allow 80/tcp
sudo ufw --force enable
sudo apt-get install libapache2-mod-proxy-html -y
sudo apt-get install libxml2-dev -y
a2enmod proxy
a2enmod proxy_html
a2enmod proxy_http/41
sed -i '$aServerName localhost' /etc/apache2/apache2.conf
service apache2 restart
cd /etc/apache2/sites-enabled
wget https://pastebin.com/raw/GbjFC2ii
cp GbjFC2ii 001-reverseproxy.conf
sudo rm /var/www/html/index.html
sudo touch /var/www/html/index.php
cat << EOF > /var/www/html/index.html
        <!doctype html>
        <head>
        </head>
        <body>
                Index ... Text
        </body>
        </html>
Script

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip:"192.168.50.50"
  config.vm.network "forwarded_port", guest:80, host:8090, auto_correct: true
  config.vm.synced_folder ".", "/var/www/html"
  config.vm.provider "virtualbox" do |vb| 
    vb.memory = "512"
  end
  config.vm.provision "shell", inline: $Script
end
